# Generated by Django 5.0.6 on 2024-06-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('SEND', 'Send'), ('REJECT', 'Reject')], default='SEND', max_length=100),
        ),
    ]
