# Generated by Django 5.0.6 on 2024-06-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_friend_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('owner', 'profile')},
        ),
    ]
